; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder
build_type = debug
;board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_LOG_COLORS=1
    -DCONFIG_ARDUHAL_LOG_COLORS
    -DUSE_GFX_LITE
lib_deps =
    https://github.com/mrcodetastic/GFX_Lite
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display
    pierremolinaro/ACAN_ESP32@^3.0.3
    http://github.com/raphweb/ESP32TimerInterrupt
    madhephaestus/ESP32AnalogRead@^0.3.0
    majicdesigns/MD_CirQueue@^1.0.3
lib_ldf_mode = chain+
